<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy Inputs to Outputs</name>
  <uuid>578bdb20-d9c3-41b0-8f58-d169f909494e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new Financial Statement Item where
        the asReportedDescription is "Empty", 
        the currency is "GBP", 
        the dateUnit is "Months", 
        the documentID is "1234", 
        the editedDescription is "Empty", 
        the finStmtType is "Undefined", 
        the lineItemValue is 0, 
        the market is "UK", 
        the nameSection is "Empty", 
        the negativeFlag is "F", 
        the reportedValue is 0, 
        the filingLength is 0, 
        the tableID is 0, 
        the rowID is 0, 
        the mainTableForeignKey is 0, 
        the pageNumber is "0", 
        the periodicity is "Years", 
        the presentationFormat is "Undefined", 
        the statementDate is 10/9/2020, 
        the tableIndex is 0, 
        the tableName is "Empty" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
