<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>scikitModel</name>
  <uuid>04d5ffeb-100d-413f-97f4-0d3844399509</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to predict( 'Input mapping' ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
