<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map Output</name>
  <uuid>ce5be0a0-c9ee-433c-8a41-4251ae1063a4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 99 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
