<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy FCC Prediction</name>
  <uuid>95d4974b-9352-455c-b289-92ef493ed393</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the prediction of 'ML model invocation'  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
