<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Complex Lookup</name>
  <uuid>606ffbd4-89a2-4f1d-b4da-21046446e6e4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
    set 'value from lookup' to the complex lookup computed from 
    Input being "XYZ";  
then
print "Complex lookup : " + 'value from lookup'  ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
