<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy Inputs to Output</name>
  <uuid>f0b08a18-b019-4a11-9152-e09d617a3ca7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each Financial Statement Item in 'Input Data' : 

- add this Financial Statement Item to decision ; 
  
       





]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
