<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Differentiated</name>
  <uuid>ad5735a8-c75c-4f73-9d9b-77d35b0024c2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
    set 'balance sheet item' to a Financial Statement Item in decision 
    where the finStmtType of this Financial Statement Item contains "BAL" ; 
     
if any of the following conditions is true : 
    - the nameSection of 'balance sheet item' contains "NON-CURRENT" 
    - the nameSection of 'balance sheet item' contains "LIABILITIES|CURRENT LIABILITIES" 
    - the nameSection of 'balance sheet item' contains "CURRENT LIABILITIES" 
    - the nameSection of 'balance sheet item' contains "CURRENT ASSETS" 
then 
    set the presentationFormat of 'balance sheet item' to "DFF" ; 
else  
    set the presentationFormat of 'balance sheet item' to "NFF" ; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
