<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Parent BAL</name>
  <uuid>8f3e5fdc-c244-49ef-b8df-46f0da7372cf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
    set 'potential child item' to a Financial Statement Item in decision ;

if 
    there is at least one Financial Statement Item in decision 
        where the finStmtType of this Financial Statement Item contains "BAL" 
        and the tableIndex of this Financial Statement Item is the mainTableForeignKey of  'potential child item' , 
then 
set the finStmtType of 'potential child item' to "BAL-P" ;
print "Found a parent balance sheet in table ID " + the tableID of 'potential child item' ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
