<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Set Default Values</name>
  <uuid>77e92ecb-1eb8-4a9c-b796-cb0c8b5bfb08</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each Financial Statement Item in decision : 
    - set the finStmtType of this Financial Statement Item to "Undefined"  
    - set the presentationFormat of this Financial Statement Item to "Undefined" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
