<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy Input to Output</name>
  <uuid>9ab68a6a-f9ae-4106-8c08-00572493ff40</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Input ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
