<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>map output</name>
  <uuid>2b43508c-d3e7-4553-aaa5-1001f4054252</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the prediction of 'ML model invocation'  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
