<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy FCC Prediction</name>
  <uuid>a5947f76-1d4c-41b3-9647-04971944cf0e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the prediction of 'ML model invocation'  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
