<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy</name>
  <uuid>8b60d8fc-b3cf-4876-95b1-928679be1048</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[then
    set decision to a new ML model input where
        the values is Input  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
