<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>050c652b-5bad-4ddd-acb3-127d37d2f03e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
