<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>fcc-Dt</name>
  <uuid>50e5bd7f-cfc0-4ac2-ac3a-cfb455756bd6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to predict( 'Input mapping' ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
