<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Copy Inputs to Outputs</name>
  <uuid>71991345-ee29-4800-be47-299e22496400</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each Financial Statement Item in 'Balance Sheets' :  

- add this Financial Statement Item to decision ; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
