<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Lookup FCC</name>
  <uuid>fcc43273-3642-483d-96de-5b6be605076f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
    set 'this item' to a Financial Statement Item in decision ; 
then
    set the fccCoding of 'this item' to the fcc dt computed from 
    Financial Item to Classify being 'this item'; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
